### ISSUE TITLE
ValueError: not enough values to unpack (expected 6, got 5)

### ISSUE THREAD

**Issue by DDxk369** [StarUniversus/gcmae#2]
Hello, thank you for the code you disclosed, which is very helpful to me, but there is such a mistake in the process of reproduction, it seems that some calculation is missing?

[01:56:08.869980] number of params (M): 85.80
[01:56:08.870021] base lr: 1.00e-03
[01:56:08.870036] actual lr: 5.00e-04
[01:56:08.870049] accumulate grad iterations: 1
[01:56:08.870061] effective batch size: 128
[01:56:08.873025] criterion = LabelSmoothingCrossEntropy()
[01:56:08.873560] Auto resume checkpoint: output/fine_gcmae_base_patch16_224/checkpoint-0.pth
[01:56:09.664537] Resume checkpoint output/fine_gcmae_base_patch16_224/checkpoint-0.pth
[01:56:10.356067] With optim & sched!
[01:56:10.398492] Start training for 5 epochs
[01:56:10.399643] log_dir: ./log
[01:56:32.592227] Epoch: [1]  [0/8]  eta: 0:02:57  lr: 0.000100  loss: 0.6482 (0.6482)  time: 22.1914  data: 17.0879  max mem: 13674
[01:56:47.641381] Epoch: [1]  [7/8]  eta: 0:00:04  lr: 0.000188  loss: 0.6341 (0.6341)  time: 4.6550  data: 2.1361  max mem: 14016
[01:56:48.198151] Epoch: [1] Total time: 0:00:37 (4.7248 s / it)
[01:56:48.198262] Averaged stats: lr: 0.000188  loss: 0.6341 (0.6341)
[01:57:02.893200] Test:  [0/5]  eta: 0:00:54  loss: 1.1797 (1.1797)  acc1: 0.0000 (0.0000)  acc5: 0.0000 (0.0000)  time: 10.9977  data: 10.2477  max mem: 14016
[01:57:05.581299] Test:  [4/5]  eta: 0:00:02  loss: 0.3041 (0.5356)  acc1: 100.0000 (67.7064)  acc5: 100.0000 (67.7064)  time: 2.7370  data: 2.0496  max mem: 14016
[01:57:06.198718] Test: Total time: 0:00:14 (2.8608 s / it)
[01:57:06.215266] * Acc@1 67.706 Acc@5 67.706 loss 0.536 acc 0.677 auc 0.791
Traceback (most recent call last):
  File "main_finetune.py", line 367, in <module>
    main(args)
  File "main_finetune.py", line 335, in main
    test_stats, auc, precision, recall, f1, specificity = evaluate(data_loader_val, model, device, args.nb_classes)
ValueError: not enough values to unpack (expected 6, got 5)

**Comment by StarUniversus** [comment]
Hi, thank you for your interest and questions.
This fix has been committed and tested in the following environments
`Python 3.6.13
torch 1.9.1+cu111
torchvision 0.10.1+cu111`
